-- CARNILAB SHOP SYSTEM
-- Tablas para el manejo de catálogo público y pedidos

-- 1. TABLA PRODUCTOS
create table if not exists public.shop_products (
  id bigint generated by default as identity primary key,
  owner_key text not null, -- Vincula al vendedor
  title text not null,
  description text,
  price numeric default 0,
  stock integer default 1,
  image_url text, -- URL de la foto
  category text, -- 'plant', 'supply', 'merch'
  active boolean default true,
  created_at timestamptz default now()
);

-- Indices para velocidad
create index if not exists idx_shop_products_owner on public.shop_products(owner_key);

-- RLS PRODUCTOS
alter table public.shop_products enable row level security;

-- Politica 1: Vendedores ven y editan SUS productos
create policy "Sellers manage own products" 
on public.shop_products
for all
using (owner_key = current_setting('request.headers')::json->>'x-carnilab-key' 
    or owner_key = (select key from access_keys where device_id = auth.uid() limit 1));

-- Politica 2: PUBLICO puede VER productos activos (Catalogo)
create policy "Public view products" 
on public.shop_products
for select
using (active = true);


-- 2. TABLA PEDIDOS (ORDERS)
create table if not exists public.shop_orders (
  id bigint generated by default as identity primary key,
  owner_key text not null, -- A quien le compraron
  customer_name text not null,
  customer_contact text not null, -- WhatsApp
  items jsonb not null, -- [{id, title, price, qty}...]
  total numeric not null,
  status text default 'pending', -- 'pending', 'paid', 'shipped', 'cancelled'
  created_at timestamptz default now()
);

-- Indices
create index if not exists idx_shop_orders_owner on public.shop_orders(owner_key);

-- RLS PEDIDOS
alter table public.shop_orders enable row level security;

-- Politica 1: PUBLICO puede CREAR pedidos (Insert only)
create policy "Public create orders" 
on public.shop_orders
for insert
with check (true); 

-- Politica 2: Vendedor ve SUS pedidos recibidos
create policy "Seller view orders" 
on public.shop_orders
for select
using (owner_key = current_setting('request.headers')::json->>'x-carnilab-key' 
    or owner_key = (select key from access_keys where device_id = auth.uid() limit 1));

-- Politica 3: Vendedor actualiza estado de pedidos
create policy "Seller update orders" 
on public.shop_orders
for update
using (owner_key = current_setting('request.headers')::json->>'x-carnilab-key' 
    or owner_key = (select key from access_keys where device_id = auth.uid() limit 1));
