-- 1. Asegurar que la tabla crosses existe y tiene las columnas correctas
create table if not exists crosses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  owner_key text not null,
  nombre text not null,
  madre_nombre text not null,
  madre_especie text,
  padre_nombre text not null,
  padre_especie text,
  padres_extra jsonb default '[]'::jsonb,
  fecha_cruza date,
  fecha_germinacion date,
  semillas_obtenidas int default 0,
  plantas_germinadas int default 0,
  estado text default 'en_proceso',
  notas text,
  madre_imagen text,
  padre_imagen text,
  hibrido_imagen text
);

-- 2. Asegurar que las columnas nuevas existan (si la tabla ya existía)
alter table crosses add column if not exists owner_key text;
alter table crosses add column if not exists padres_extra jsonb default '[]'::jsonb;
alter table crosses add column if not exists madre_imagen text;
alter table crosses add column if not exists padre_imagen text;
alter table crosses add column if not exists hibrido_imagen text;

-- 3. Habilitar RLS
alter table crosses enable row level security;

-- 4. Crear políticas de seguridad (RLS)
-- Permitir todo al dueño de la cruza
drop policy if exists "Owner Access Crosses" on crosses;
create policy "Owner Access Crosses"
  on crosses for all
  using ( owner_key = (select key from access_keys where device_id = auth.uid() limit 1) )
  with check ( owner_key = (select key from access_keys where device_id = auth.uid() limit 1) );

-- Política de respaldo para insertar si no existe la anterior (para evitar bloqueos)
drop policy if exists "Enable insert for authenticated users only" on crosses;
create policy "Enable insert for authenticated users only"
  on crosses for insert
  with check ( auth.role() = 'authenticated' );
