-- 1. Ensure 'slug' column exists in access_keys
alter table access_keys add column if not exists slug text;

-- 2. Ensure 'slug' is unique
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'access_keys_slug_key') then
    alter table access_keys add constraint access_keys_slug_key unique (slug);
  end if;
end $$;

-- 3. Backfill missing slugs for existing users
-- Generates a random slug based on label or random string if null
update access_keys 
set slug = lower(regexp_replace(coalesce(label, 'user'), '[^a-zA-Z0-9]', '-', 'g')) || '-' || substr(md5(random()::text), 1, 4)
where slug is null;

-- 4. Ensure RLS is enabled
alter table access_keys enable row level security;
alter table plants enable row level security;
alter table inbox_messages enable row level security;

-- 5. Drop existing policies to avoid conflicts/duplicates
drop policy if exists "Public Access Keys Read" on access_keys;
drop policy if exists "Public Plants Read" on plants;
drop policy if exists "Public Inbox Insert" on inbox_messages;

-- 6. Re-create policies
-- Allow public to find nursery by slug (READ ONLY)
create policy "Public Access Keys Read"
  on access_keys for select
  using ( true );

-- Allow public to see plants (READ ONLY)
create policy "Public Plants Read"
  on plants for select
  using ( true );

-- Allow public to send messages (INSERT ONLY)
create policy "Public Inbox Insert"
  on inbox_messages for insert
  with check ( true );

-- 7. Ensure inbox_messages table exists (Idempotent)
create table if not exists inbox_messages (
  id bigint generated by default as identity primary key,
  owner_key text not null,
  sender_name text not null,
  sender_contact text not null,
  message text not null,
  plant_id bigint references plants(id),
  plant_name text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
