-- Script para crear/reparar la tabla seed_bank en Supabase
-- Ejecutar en el SQL Editor de Supabase
-- IMPORTANTE: Ejecutar paso a paso si hay errores

-- 1. Crear la tabla si no existe
CREATE TABLE IF NOT EXISTS seed_bank (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  owner_key TEXT NOT NULL,
  nombre TEXT NOT NULL,
  especie TEXT,
  cantidad INT DEFAULT 0,
  fecha_ingreso TIMESTAMP WITH TIME ZONE,
  origen TEXT DEFAULT 'propia',
  cross_id BIGINT,
  estado TEXT DEFAULT 'almacenada',
  inicio_estratificacion TIMESTAMP WITH TIME ZONE,
  fin_estratificacion TIMESTAMP WITH TIME ZONE,
  notas TEXT
);

-- 2. Agregar columnas si faltan (para tablas existentes)
ALTER TABLE seed_bank ADD COLUMN IF NOT EXISTS owner_key TEXT;
ALTER TABLE seed_bank ADD COLUMN IF NOT EXISTS especie TEXT;
ALTER TABLE seed_bank ADD COLUMN IF NOT EXISTS cross_id BIGINT;
ALTER TABLE seed_bank ADD COLUMN IF NOT EXISTS inicio_estratificacion TIMESTAMP WITH TIME ZONE;
ALTER TABLE seed_bank ADD COLUMN IF NOT EXISTS fin_estratificacion TIMESTAMP WITH TIME ZONE;

-- 2b. Si las columnas existen como DATE, cambiarlas a TIMESTAMP
-- (Ejecutar solo si da error por tipo incompatible)
-- ALTER TABLE seed_bank ALTER COLUMN inicio_estratificacion TYPE TIMESTAMP WITH TIME ZONE;
-- ALTER TABLE seed_bank ALTER COLUMN fin_estratificacion TYPE TIMESTAMP WITH TIME ZONE;

-- 3. Habilitar RLS
ALTER TABLE seed_bank ENABLE ROW LEVEL SECURITY;

-- 4. Crear políticas de seguridad (RLS)
DROP POLICY IF EXISTS "Owner Access SeedBank" ON seed_bank;
CREATE POLICY "Owner Access SeedBank"
  ON seed_bank FOR ALL
  USING ( owner_key = (SELECT key FROM access_keys WHERE device_id = auth.uid() LIMIT 1) )
  WITH CHECK ( owner_key = (SELECT key FROM access_keys WHERE device_id = auth.uid() LIMIT 1) );

-- Política de respaldo para insertar
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON seed_bank;
CREATE POLICY "Enable insert for authenticated users only"
  ON seed_bank FOR INSERT
  WITH CHECK ( auth.role() = 'authenticated' );

-- 5. Crear índice para mejorar performance
CREATE INDEX IF NOT EXISTS idx_seed_bank_owner_key ON seed_bank(owner_key);
CREATE INDEX IF NOT EXISTS idx_seed_bank_cross_id ON seed_bank(cross_id);
