-- Enable RLS on tables if not already enabled
alter table access_keys enable row level security;
alter table plants enable row level security;
alter table inbox_messages enable row level security;

-- 1. Allow public to find nursery by slug (READ ONLY)
create policy "Public Access Keys Read"
  on access_keys for select
  using ( true );

-- 2. Allow public to see plants (READ ONLY)
create policy "Public Plants Read"
  on plants for select
  using ( true );

-- 3. Allow public to send messages (INSERT ONLY)
create policy "Public Inbox Insert"
  on inbox_messages for insert
  with check ( true );

-- Note: We assume 'inbox_messages' table exists. If not, create it:
create table if not exists inbox_messages (
  id bigint generated by default as identity primary key,
  owner_key text not null,
  sender_name text not null,
  sender_contact text not null,
  message text not null,
  plant_id bigint references plants(id),
  plant_name text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
